### ISSUE TITLE
Current milestones

### ISSUE THREAD

**Issue by olefasting** [fishfight/FishFight#202]
This is a list of current milestones, which we aim to finish within the next three weeks.

The primary items are based on my own estimation of what I, alone, can finish in that time period, so if you want to do some of the secondary ones, or something completely different, that is fine, too!

## Primary goals

- [ ] Implement input mapping from config file (see #139)
- [ ] Create UI for changing settings and input mapping
- [ ] Mod support and a re-skin of the module management menu from [rust_rpg_toolkit](https://github.com/olefasting/rust_rpg_toolkit) (see #192)
- [ ] Create schemas for all the JSON data models (see JSON files in `assets/**`), for schema validation github workflow (see #187)
- [ ] Autotiling for the editor (see #203)
- [ ] Design and implement a gamepad input scheme for the editor (easy jumping between toolbars with bumpers etc.)
- [ ] Texture support for our `macroquad-particles` [fork](https://github.com/olefasting/macroquad_particles), so that we can add the new explosions, designed by @PixelFrog123 Alternatively, we can hack together a temporary system for this, using `AnimationPlayer`, until we make a proper, optimized version using more low-level approaches in `macroquad-particles`. (see #185)

## Secondary goals

Feel free to propose additions to the list or voice any comments or criticism you might have to it!

**Comment by Chosenundead15** [comment]
I think I can work on the editor to place object, I tried to use it for that in the pass and it wasn't ready, so it looks like a good opportunity to work on it myself.

**Comment by olefasting** [comment]
allright! give me a shout if you need any help

**Comment by olefasting** [comment]
Also, items should fetch the sprite from the ItemParams entry in Resources, for draw. For EnvironmentItems you can just check if they are sproingers and draw a sproinger, if so, for now, as I have not completed that part

**Comment by olefasting** [comment]
I'm closing this as we have completed the current sprint and so that we can track future milestones in individual track issues, as I believe was intended by @erlend-sh
